<?php
View::partial('inventario/header');
View::content();
View::partial('inventario/nav');
?>

<?php echo Html::link('user/crear', '<i class="icon-plus-sign"></i>  <i class="icon-user"></i>', 'class="btn btn-success" title="Nuevo Usuario"');?>

<br>
<br>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>id</th>
			<th>Nombre de Usuario</th>
			<th>Tipo de Usuario</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($usuarios->items as $item) : ?>
		<tr>
			<td><?php echo $item->id?></td>
			<td><?php echo $item->nombre?></td>
			<td><?php if ($item->tipo == 't') {print "Administrador";} else {print "Basico";}?>
			<td>
				<?php $nombre = trim($item->nombre);?>
				&nbsp; <?php echo Html::link("user/modificar/$item->id", '<i class="icon-edit icon-white"></i>', 'class="btn btn-inverse" title="Modificar el Tipo de Cuenta"');?>
				&nbsp; <?php echo Js::link("user/eliminar/$item->id", '<i class="icon-trash icon-white"></i>', $confirm = "¿Esta Seguro de que desea Eliminar el Usuario {$nombre} del Sistema?", $class = 'btn btn-danger');?>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<ul class="pager">
  <li class="previous">
    <?php if($usuarios->prev) echo Html::linkAction("consulta/$usuarios->prev/", '&larr; Anterior');?>
  </li>
  <li class="next">
    <?php if($usuarios->next) echo Html::linkAction("consulta/$usuarios->next/", 'Próximo &rarr;');?>
  </li>
</ul>