<?php
View::partial('inventario/header');
View::content();
View::partial('inventario/nav');
?>

<div class="page-header">
	<h1>
		Modulo Usuarios <small>Modificar Datos de Usuario.</small>
	</h1>
</div>
<div class="row-fluid">
	<div class="span4">
		<?php echo Form::open('', $method='POST','class="form-horizontal"');?>
		<fieldset>
			<legend>Modificar Permisologia de la Cuenta</legend>


			<div class="control-group">
				<label class="control-label" for="input01">Tipo de Usuario</label>
				<div class="controls">
					<?php 
					$data = array(''=>'Seleccione una Opcion','0'=>'Basico',
							'1'=>'Administrativo');
					?>
					<?php echo Form::select('usuarios.tipo', $data);?>
				</div>
			</div>

			<div class="form-actions">
				<?php echo Form::hidden('usuarios.id');?>
				<?php echo Form::hidden('usuarios.nombre');?>
				<?php echo Form::hidden('usuarios.password');?>
				<?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"');?>
				&nbsp;
			</div>
		</fieldset>
		<?php echo Form::close();?>
	</div>
</div>