<div class="span4">
	<div class="well" style="padding: 8px 0;">
		<ul class="nav nav-list">
			<li class="nav-header">Gestion de Articulos</li>
			<li><?php echo Html::link('articulos/agregar', '<i class="icon-plus-sign"></i> Ingresar Articulo');?>
			</li>
			<li><?php echo Html::link('articulos/consulta', '<i class="icon-search"></i> Consultar Articulo');?>
			</li>
			<li><?php echo Html::link('articulos/modificar', '<i class="icon-edit"></i> Modificar Articulo');?>
			</li>
			<li><?php echo Html::link('articulos/minimo', '<i class="icon-minus-sign"></i> Minimo Inventario');?>
			</li>
			<li><?php echo Html::link('articulos/eliminar', '<i class="icon-trash"></i> Eliminar Articulo');?>
			</li>
		</ul>
	</div>
</div>
