<div class="span4">
	<div class="well" style="padding: 8px 0;">
		<ul class="nav nav-list">
			<li class="nav-header">Funciones Principales</li>
			<li><a href="#"><i class="icon-shopping-cart"></i> Ventas</a></li>
			<li><a href="#"><i class="icon-inbox"></i> Ordenes de Pago</a></li>
			<li><?php echo Html::link('articulos/index', '<i class="icon-list-alt"></i> Articulos</a>');?></li>
		</ul>
	</div>
</div>