<div class="span4">
	<div class="well" style="padding: 8px 0;">
		<ul class="nav nav-list">
			<li class="nav-header">Gestion de Proveedores</li>
			<li><?php echo Html::link('articulos/agregar', '<i class="icon-plus-sign"></i> Ingresar Provedor');?>
			</li>
			<li><?php echo Html::link('articulos/consulta', '<i class="icon-search"></i> Consultar Provedores');?>
			</li>
			<li><?php echo Html::link('articulos/modificar', '<i class="icon-edit"></i> Modificar Provedores');?>
			</li>
			<li><?php echo Html::link('articulos/eliminar', '<i class="icon-trash"></i> Eliminar Provedor');?>
			</li>
		</ul>
	</div>
</div>
