<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<?php echo Html::link('menu/index', 'Sistema de Inventario', 'class="brand"');?>

			<ul class="nav">
				<li><?php echo Html::link('proveedor/index', '<i class="icon-briefcase icon-white"></i> Proveedores');?>
				</li>
				<li><a href="#"><i class="icon-shopping-cart icon-white"></i> Ventas</a>
				</li>
				<li><a href="#"><i class="icon-inbox icon-white"></i> Ordenes de Pago</a>
				</li>
			</ul>

			<div class="nav-collapse">
				<ul class="nav">
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown"><i class="icon-lock icon-white"></i>  Administracion <b class="caret"></b>
					</a>
						<ul class="dropdown-menu">

							<li class="divider"></li>
							
							<li><?php  
							if (Auth::get('tipo') == 't'){
								echo Html::link('articulos/index', '<i class="icon-list-alt"></i> Gestion de Articulos');
							}?></li>
							<li><a href="#"><i class="icon-user"></i> Gestion de Usuarios</a>
							</li>
						</ul></li>
				</ul>

				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
					<li>
						<div class="btn-group">
							<a class="btn btn-primary" href="#"><i
								class="icon-user icon-white"></i> <?php echo Auth::get('nombre'); ?>
							</a> <a class="btn btn-primary dropdown-toggle"
								data-toggle="dropdown" href="#"><span class="caret"></span> </a>
							<ul class="dropdown-menu">

								<li class="divider"></li>
								<li><?php echo Html::link('user/logout', '<i class="icon-off"></i>Salir');?>
								</li>
							</ul>
						</div>
					</li>
				</ul>
			</div>
			<!-- /.nav-collapse -->
		</div>
	</div>
</div>
