<?php 
View::content();
View::partial('inventario/header');
View::partial('inventario/nav');
?>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Codigo de Articulo</th>
			<th>Descripcion</th>
			<th>Stock</th>
			<th>P.V.P</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($lista->items as $item) : ?>
		<tr>
			<td><?php echo $item->codart?></td>
			<td><?php echo $item->descripcion?></td>
			<td><?php echo $item->stock?></td>
			<td><?php echo $item->precio?></td>
			<td>
			<?php echo Html::link("articulos/ver/$item->id", '<i class="icon-eye-open icon-white"></i>', 'class="btn btn-info" title="Ver"');?>
			&nbsp;
			<?php echo Html::link("articulos/modificar/$item->id", '<i class="icon-edit icon-white"></i>', 'class="btn btn-inverse" title="Modificar"');?>
			&nbsp;
			<?php echo Html::link("articulos/eliminar/$item->id", '<i class="icon-trash icon-white"></i>', 'class="btn btn-danger" title="Eliminar"');?>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

