<?php 
View::content();
View::partial('inventario/header');
View::partial('inventario/nav');
?>

<?php echo Form::text('autocomplete') ?> <i class="icon-search"></i>
 
<script type="text/javascript" >
    $(document).ready(function(){
        $('input#autocomplete').autocomplete({
 
            minLength : 2 , //le indicamos que busque a partir de haber escrito dos o mas caracteres en el input
 
            source : function( request , response ){
 
                var url = "<?php echo PUBLIC_PATH ?>articulos/autocomplete";   //url donde buscará los estados
 
                $.post(url, { 'busqueda' : request.term }, response, 'json');
 
                //busqueda es la varible que mandaremos por post con el contenido del input
            }
        });
    });
</script>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Codigo de Articulo</th>
			<th>Descripcion</th>
			<th>Stock</th>
			<th>P.V.P</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<?php ?>
	<tbody>
		<?php foreach ($lista->items as $item) : ?>
		<tr>
			<td><?php echo $item->codart?></td>
			<td><?php echo $item->descripcion_art?></td>
			<td><?php echo $item->stock?></td>
			<td><?php echo $item->precio?></td>
			<td><?php echo Html::link("articulos/ver/$item->id/$item->categoria_id", '<i class="icon-eye-open icon-white"></i>', 'class="btn btn-info" title="Ver"');?>
				&nbsp; <?php echo Html::link("articulos/modificar/$item->id", '<i class="icon-edit icon-white"></i>', 'class="btn btn-inverse" title="Modificar"');?>
				&nbsp; <?php echo Js::link("articulos/eliminar/$item->id", '<i class="icon-trash icon-white"></i>', $confirm = "¿Esta Seguro de que desea Eliminar el aritculo {$item->codart} del inventario?", $class = 'btn btn-danger');?>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>