<?php
View::content();
View::partial('inventario/header');
View::partial('inventario/nav');
?>

<div class="page-header">
	<h1>
		Modulo Articulos <small>Modificar Articulos.</small>
	</h1>
</div>
<div class="row-fluid">
	<div class="span4">
		<?php echo Form::open('', $method='POST','class="form-horizontal"');?>
		<fieldset>
			<legend>Ingrese los Datos</legend>
			<div class="control-group">
				<label class="control-label">Codigo de Articulo:</label>
				<div class="controls">
					<?php echo Form::text('articulos.codart', 'class=".span2"');?>
				</div>
				<p class="help-block">Igual o no menor a 4 caracteres ( A-Z, a-z,
					0-9).</p>
			</div>
			
			<div class="control-group">
				<label class="control-label">Categoria:</label>
				<div class="controls">
					<?php echo Form::dbSelect('articulos.id_cat', 'nombre', array('categoria','find'), 'Seleccione una categoria');?>
				</div>
				<div class="controls"><?php echo Html::link('categoria/agregar', '<i class="icon-plus"></i>Agregar Categoria');?></div>
			</div>

			<div class="control-group">
				<label class="control-label">Descripcion del Articulo:</label>
				<div class="controls">
					<?php echo Form::textarea('articulos.descripcion', '');?>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="appendedPrependedInput">Stock: </label>
				<div class="controls">
					<div class="input-prepend input-append">
						<span class="add-on">Cant.</span><?php echo Form::text('articulos.stock', 'class="input-small"');?>
					</div>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="appendedPrependedInput">Precio P.V.P</label>
				<div class="controls">
					<div class="input-prepend input-append">
						<span class="add-on">Bs.F</span><?php echo Form::text('articulos.precio', 'class="input-small"');?><span
							class="add-on">.00</span>
					</div>
				</div>
			</div>
			
			<div class="control-group">
				<label class="control-label">Minimo en Inventario:</label>
				<div class="controls">
					<?php echo Form::text('articulos.minimo', 'class="input-small"');?>
				</div>
			</div>

			<div class="form-actions">
				<?php echo Form::hidden('articulos.id');?>
				<?php echo Form::submit('Actualizar Datos', 'class="btn btn-primary"');?>
				&nbsp;
			</div>
		</fieldset>
		<?php echo Form::close();?>
	</div>
</div>